import { Footer } from '@content/components/navigation/footer'
import { Header } from '@content/components/navigation/header'
import { ThemeProvider } from '@content/providers/theme'
import { ScrollArea } from '@web/components/ui/scroll-area'
import '@web/core/global.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
} satisfies Metadata

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ThemeProvider>
          <ScrollArea className="h-screen">
            <div className="flex h-screen flex-col bg-background">
              <div className="sticky top-0 z-50 w-full border-b border-border/40 bg-background/95 backdrop-blur supports-[backdrop-filter]:bg-background/60">
                <Header />
              </div>
              {props.children}
              <Footer />
            </div>
          </ScrollArea>
        </ThemeProvider>
      </body>
    </html>
  )
}
