import '@dinstack/ui/styles/globals.css'
import { Toaster } from '@dinstack/ui/toaster'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { HistoryProvider } from './_providers/history'
import { QueryProvider } from './_providers/query'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${inter.className} h-screen`}>
        <HistoryProvider>
          <QueryProvider>
            {children}
            <Toaster />
          </QueryProvider>
        </HistoryProvider>
      </body>
    </html>
  )
}
