import { ScrollArea } from '@dinstack/ui/scroll-area'
import '@dinstack/ui/styles/globals.css'
import { Toaster } from '@dinstack/ui/toaster'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { HistoryProvider } from './_providers/history'
import { QueryProvider } from './_providers/query'
import { StoresProvider } from './_providers/stores'
import { ThemeProvider } from './_providers/theme'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`${inter.className}`} suppressHydrationWarning>
        <StoresProvider>
          <ThemeProvider attribute="class" defaultTheme="system">
            <HistoryProvider>
              <QueryProvider>
                <ScrollArea>
                  <div className="h-screen">{children}</div>
                </ScrollArea>
                <Toaster />
              </QueryProvider>
            </HistoryProvider>
          </ThemeProvider>
        </StoresProvider>
      </body>
    </html>
  )
}
